name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

permissions:
  contents: read

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: gradle

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Rename APK
        run: |
          for f in app/build/outputs/apk/debug/*-debug.apk; do
            [ -e "$f" ] || continue
            mv "$f" "${f/-debug/}"
          done

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/outputs/apk/debug/*.apk
